version: '3'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 run:app
    volumes:
      - .:/app
      - static_volume:/studyforge/web/static
      - C:/Users/User/.bitcoinlib:/app/wallets
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/studyforge/static
    depends_on:
      - web
    networks:
      - webnet
volumes:
  static_volume:
networks:
  webnet:
