version: '3'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 run:app
    volumes:
      - .:/app
      - static_volume:/app/web/static
      - C:/Users/User/.bitcoinlib:/app/wallets
    env_file:
      - .env
    network_mode: "host"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/web/static
    network_mode: "host"
volumes:
  static_volume:
